sudo: false
language: node_js
install: true
script: ./test/travis.sh
env:
  matrix:
  - NODE=6
  - NODE=5
  - NODE=4
  - BROWSER=chrome
  - BROWSER=firefox
  - BROWSER=safari
  - BROWSER=android
  - BROWSER=iphone
  global:
  - secure: TLPWcgZtx5iH+0a7rKrJJvVDdE8MgbiKWlJxabzobYabPEPLkrbxhGt8uJilAjXOg6lEGrwvNzJC41/5T7ogvWoTPsABhPm1PQpv9Gv4ObNbRiPZGDns06s29SFqqQy0l7Wm0sq54JZzOByk6NnRQQlgcDhaxbXfhXrR617Okq0ULUEc7rWfzvrAw57pmV1MVyJOGYMGuc34f7tylgCtxxiex4Ra7JYJE9uwoyu0Bi7gbqI+pB+aoXZTHHezH0UHNBdb0OdN1P3Odz1y1PEoPN1LNeJ/stAvlESs1EbU7KRYjYeJZviDDFKCfU/yMSH6IMMUfw0Sd8uzE3+rYavyAWYw1eq7s/TOG53CcUi8mHedZSD4zWOQgaV1WeCLOUFq7BMuZHBa0Y2hXqFfXlXDrapDOwu1GlQF379kReGf3CWSQni49WbxXHpMUhQMCgnNZPeoPaAD1JbkxsEM7v6fMz52T47/iEjGXMAVnedwzUv47Z8EBXipuJeXWKk5RUoxEBtmp9MCZzLIm0LxwUtLx0d0vFTqXJowH0nh2pNx1k1gse4jpsEquso1wrFdAtk2UkduQLrAU+GAIF+MnV9vxceao33XybisxllKaFSz/WxKjG3RCzJ/1OY4l/XpvzdY0te0gWOGpUCCbQMBkc8t5nJBbHUaaQ5sEgwKGXFS97A=
  - secure: OxXGcT2odUjW/ZEBTrT65qsVmJH9nqcrL6uzCMcKFLZYm1NVkM8DjaMLXkxX+W7R7lu/o0DvJzkv5niIMrjtsjj0uSdy5GSNPvIEdG5eCMB9dalcIS5FxgWzcFC2jtwongtKMkYTu+ynyAWHGdTQTMUe4R1ig7clpewN1FCi2liw8Q0QdpsSnkqzL6gdhVPMRTs2B15eyiuYZi/A93Ea+tqimC29c9tR+Wf65uk/Ufompe3/4rgAb1ltAxTm+IQT4nE/qfstGRwdqJmzhJH3z0Qp/29Xs41jO1kPF+2toEbCZUMqC54kS37OFbgQWHO0lpMo/JSQnmYw8fg9nVvrci5BR0RKNSU6dW5tLFOgLQnh3/C8ag/5fu+88XVS5OS4anCjWgVPA2iC61qQQ8khc8xNrdxQYjKOxMoV5VTEajiOxmLnIjqT7wnjf9z0HqGO5HaETqJ4iJEb83Ipv89ndHHkKmN1WBqlqtP46NdfiqN03Cmrs0EClKqC9gnjn+RtXbeUNO8fBLE+AI5MkkiCKrn7kgb7CYdrorrv0Q6bnJ3pV6Vj0DeClu2qJ8Oa20IUQdDB+G8ObiC9jcy4k+g5xxZ1jGJS9Y31+ABk1/bLyuOl4xopQhQ4Cjgdc5gS6cREmUWwF2fHU924YS/1jhCIb6L5IwvMnzXi1nra2VFwfhs=
notifications:
  email: false
